services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mini2_6_horizon
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/mini2_6_horizon?authSource=admin
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

  postgres:
    image: postgres
    container_name: postgres_miniapp
    environment:
      POSTGRES_DB: mini2_6_horizon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: miniapp
    depends_on:
      - postgres
      - mongo
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/mini2_6_horizon
      spring.data.mongodb.uri: mongodb://root:example@mongo:27017/mini2_6_horizon?authSource=admin
      spring.datasource.username: postgres
      spring.datasource.password: 1234
